# Generated by Django 3.1.5 on 2021-01-30 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PipelineSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('twitch_client_id', models.CharField(max_length=64, null=True)),
                ('twitch_client_secret', models.CharField(max_length=64, null=True)),
                ('chat_type', models.CharField(choices=[('TW', 'twitch')], max_length=3, null=True)),
                ('twitch_chat_skip', models.DurationField(null=True)),
                ('highlights_type', models.CharField(choices=[('AVG', 'avg')], max_length=3, null=True)),
                ('avg_highlights_tic', models.DurationField(null=True)),
                ('avg_highlights_percent', models.FloatField(null=True)),
                ('avg_highlights_skip_calc', models.DurationField(null=True)),
                ('downloader_type', models.CharField(choices=[('TWV', 'twitch_vod')], max_length=3, null=True)),
                ('twitch_vod_downloader_quality', models.CharField(max_length=16, null=True)),
                ('speech_detector_type', models.CharField(choices=[('VOS', 'vosk')], max_length=3, null=True)),
                ('vosk_speech_detector_model', models.CharField(max_length=64, null=True)),
                ('uploader_type', models.CharField(choices=[('YOU', 'youtube')], max_length=3, null=True)),
                ('youtube_uploader_client_secrets', models.TextField(null=True)),
                ('youtube_uploader_credentials', models.TextField(null=True)),
                ('youtube_uploader_title', models.CharField(max_length=256, null=True)),
                ('youtube_uploader_category', models.CharField(max_length=256, null=True)),
                ('youtube_uploader_default_language', models.CharField(max_length=16, null=True)),
                ('youtube_uploader_privacy', models.CharField(max_length=32, null=True)),
                ('pipeline_name_of_compilations', models.CharField(max_length=256, null=True)),
                ('pipeline_compilation_length', models.IntegerField(null=True)),
                ('pipeline_max_of_compilations', models.IntegerField(null=True)),
                ('pipeline_to_check_music_license', models.BooleanField(null=True)),
                ('pipeline_to_cut_speech', models.BooleanField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('pipeline_settings', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_panel.pipelinesettings')),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('TW', 'twitch')], max_length=2)),
                ('auto_compile', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=256)),
                ('location', models.CharField(max_length=256)),
                ('credentials', models.TextField(null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.project')),
            ],
        ),
        migrations.CreateModel(
            name='Compilation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_location', models.CharField(max_length=256)),
                ('status', models.CharField(choices=[('AC', 'active'), ('PA', 'pause'), ('QU', 'queue'), ('PR', 'progress'), ('RE', 'ready')], default='AC', max_length=2)),
                ('pipeline_settings', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_panel.pipelinesettings')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.project')),
                ('source', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_panel.source')),
            ],
        ),
    ]
